### PR TITLE
HIP support

### PR DESCRIPTION
**Pull request by reguly**
Most apps and tests updated. Will skip HIP  tests if HIP compiler not present.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
@reguly Is there a HIP installation on any of our Warwick machines to test this ?

**Comment by gihanmudalige** [comment]
HIP tests passed.  The CI tests still have some issues.

**Comment by gihanmudalige** [comment]
There are some issues with the CI tests as you can see : https://gitlab.com/op-dsl-ci/ops-ci/-/jobs/1008845909

/home/gitlab-runner/builds/LzMTQ3QT/0/op-dsl-ci/ops-ci/ops/c/src/mpi/ops_mpi_decl_hip.cpp(40): catastrophic error: cannot open source file "hip/hip_runtime.h"
  #include <hip/hip_runtime.h>

When compiling with GNU or Intel compilers the above header files are not found.

**Comment by reguly** [comment]
For some reason CMake is trying to compile a HIP file, even though that file is not mentioned in the CMakeLists.txt. @jpmeng any idea why?

**Comment by jpmeng** [comment]
> For some reason CMake is trying to compile a HIP file, even though that file is not mentioned in the CMakeLists.txt. @jpmeng any idea why?

@reguly I will have a look as soon as possible.

**Review by gihanmudalige — APPROVED** [review]
All tests and CI tests passed

**Pull request merged**
