### PR TITLE
Code generation updates

### PR DESCRIPTION
**Pull request by reguly**
This request removes the old MPI, MPI+OpenMP codegens, and uses the same codegen for MPI, MPI+OpenMP, and combinations of these with Lazy execution. It also improves multigrid support for these.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
I am getting some compilation errors : CloverLeaf 2D (intel compilers): 

/tmp/icpc9ssP7V.o: In function `initialise_chunk()':
/home/mudalige/OPS-GIT/OPS/apps/c/CloverLeaf/initialise_chunk_ops.cpp:76: undefined reference to `ops_par_loop_initialise_chunk_kernel_xx(char const*, ops_block_core*, int, int*, ops_arg, ops_arg)'
/home/mudalige/OPS-GIT/OPS/apps/c/CloverLeaf/initialise_chunk_ops.cpp:80: undefined reference to `ops_par_loop_initialise_chunk_kernel_yy(char const*, ops_block_core*, int, int*, ops_arg, ops_arg)'

Can you try the test.sh in CloverLeaf 2D ?

**Comment by reguly** [comment]
Updated and fixed - please run the usual tests

**Comment by gihanmudalige** [comment]
Could you check: in OPS/apps/c/multiDim/
$MPI_INSTALL_PATH/bin/mpirun -np 10 ./multidim_mpi_opencl OPS_CL_DEVICE=0 OPS_BLOCK_SIZE_X=256 OPS_BLOCK_SIZE_Y=1

I seem to be not getting an output PASSED/FAIL here.

**Comment by reguly** [comment]
I am just running this - this particular test is overpartitioning. I am reducing the numebr of MPI processes in test.sh

**Comment by gihanmudalige** [comment]
The latest updates seem to have broken CloverLeaf 2D validation for MPI. 

One of the diffs is in: MPI_OpenMP/initialise_chunk_kernel_xx_cpu_kernel.cpp

-  #ifdef OPS_MPI
-  sub_dat_list sd = OPS_sub_dat_list[args[0].dat->index];
-  arg_idx[0] = MAX(0,sd->decomp_disp[0]);
-  arg_idx[1] = MAX(0,sd->decomp_disp[1]);
-  #else //OPS_MPI
+  #ifndef OPS_MPI
   arg_idx[0] = 0;
   arg_idx[1] = 0;
   #endif //OPS_MPI

**Comment by reguly** [comment]
Bleh... fixed.

**Comment by gihanmudalige** [comment]
ADI C app is not compiling. Reason being the various ops tridiag libs are not linked. How do we want to do this ?
Originally these ops wrapper functions were put in to the respective seq, mpi, cuda libs.

**Comment by reguly** [comment]
Pushed a patched makefile

**Comment by gihanmudalige** [comment]
Ok. Good to go.

**Comment by gihanmudalige** [comment]
Hold on .. need to test Fortran apps !

**Comment by gihanmudalige** [comment]
Unfortunately I am getting :
This test is considered PASSED
============> Running CUDA
0: copyout Memcpy (host=0x1aa4050, dev=0x2303f20000, size=96) FAILED: 77(an illegal memory access was encountered)

For both Fortran multiDim and multiDim3D  
This is with the PGI compilers

**Comment by reguly** [comment]
Pushed a fix for CUDA. THough buth CUDA and OpenACC break with current master and PGI 19.4. CUDA now does work, OpenACC still not. However, these are unrelated issues to this pull req.

**Pull request merged**
