### PR TITLE
Feature/makefiles

### PR DESCRIPTION
**Pull request by reguly**
Cleans up the makefiles for backends and apps, providing a template. Can set IEEE=1 or FAST=1 to set additional optimisation flags. Should be tested with all the compilers.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Are we attempting to conform to some naming convention here ?
Intel mpi uses mpicxx instead of mpic++

**Comment by reguly** [comment]
No, because MPI’s namings and paths can be all over the place. However, the makefile is constructed so if the user does define the MPICC or MPICPP variables, then those will be used, instead of the ones in Makefile.mpi. Same applies for the MPI include paths and lib paths.

Cheers,
István

**Comment by gihanmudalige** [comment]
Can you try 
./cloverleaf_openacc OPS_BLOCK_SIZE_X=64 OPS_BLOCK_SIZE_Y=4
This currently fails to validate.
I am using PGI 15.10

**Comment by reguly** [comment]
Does work and validate for me on Kepler and Pascal with 18.4 compilers.

**Comment by gihanmudalige** [comment]
Is this the larger problem that runs for 2955 iterations ?

**Comment by reguly** [comment]
Yes, that's the one. Did you compile with IEEE=1?

**Comment by gihanmudalige** [comment]
ok .. just got it passed with a different PGI compiler. Now running the full set of test on CloverLeaf 2D again just to double check

**Comment by gihanmudalige** [comment]
Ok.. All of the CloverLeaf 2D tests are passing. But I get the following issue that breaks the whole test process due to a non zero exit status:

Test problem 3 is within 1.998401444325282E-13 % of the expected solution
This test is considered PASSED

Total Wall time 56.174032
call to cuCtxDestroy returned error 201: Invalid context
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[56771,1],1]
  Exit code:    1
--------------------------------------------------------------------------

I have not had time to look into this, but perhaps you have a quick answer ?

**Comment by reguly** [comment]
Which variant is this?

**Comment by gihanmudalige** [comment]
This is cloverleaf 2D mpi+openacc

**Comment by reguly** [comment]
We were just missing the return 0 from the end of main(). Pushed a fix.

**Comment by gihanmudalige** [comment]
That also requires numawrap2 to fix the error  .. on top of your push

**Comment by gihanmudalige** [comment]
Ok .. CloverLeaf 2D and 3D both pass tests .. it seems now the HDF5 version of CloverLeaf 3D is not working. Specifically the generate_file and gemerate_file_mpi versions of the HDF5 file generating apps in this directory produces different HDF5 files. Once generated via the generate_file app running generate_file_mpi seems to break the tests. See the initial tests in tests.sh under this directory.  I have just been running the current master and this problem does not occur there.

**Comment by gihanmudalige** [comment]
OK, I think all of CloverLeaf (2D, 3D, 3D_HDF5) is passing the tests. Not sure what was the issue before, but I did have to switch compilers (PGI versions). This will be tested again with the overall tests later.

Now the issue is the use of ./OpenCL/$(SEQ_KERNELS)

I know that we used the SEQ_KERNELS in some of the OpenCL backends. But complex_numbers example is breaking due to this.

**Comment by reguly** [comment]
Pushed a slightly hacky fix - I create an empty file if it does not exist after code generation is done.

**Comment by gihanmudalige** [comment]
ok .. I was scratching my head as to how to do this .. will continue testing.

**Comment by gihanmudalige** [comment]
Here are some of the issues I currently have :

**********************************
complex_numbers - PGI compilers


/mudalige/OPS-GIT/OPS/ops/c/include -I/home/mgiles/mudalige/hdf5-pgi-mpich//include \
			        -I. MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.c -c -o MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.o
PGC-S-0029-Syntax error: Recovery attempted by deleting from identifier z on line 23 to just before ';' on line 23 (MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.c: 23)
PGC-S-0043-Redefinition of symbol, __complex__ (MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.c: 24)
PGC-S-0029-Syntax error: Recovery attempted by deleting from identifier coeff on line 24 to just before ';' on line 24 (MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.c: 24)
PGC-S-0039-Use of undeclared variable coeff (MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.c: 27)
PGC-S-0039-Use of undeclared variable z (MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.c: 27)
PGC-S-0039-Use of undeclared variable coeff (MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.c: 27)
PGC-S-0037-Syntax error: Recovery attempted by deleting identifier __real__ (MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.c: 28)
PGC-S-0037-Syntax error: Recovery attempted by deleting identifier __imag__ (MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel_c.c: 29)
PGC/x86-64-Extractor Linux 16.9-0: completed with severe errors
make: *** [MPI_inline/complex_numbers_block0_cn_kernel_mpiinline_kernel.o] Error 2

**********************************

octon {feature/makefiles} ~/OPS-GIT/OPS/apps/c/multiDim$ $MPI_INSTALL_PATH/bin/mpirun -np 2 ./multidim_mpi_openacc OPS_BLOCK_SIZE_X=32 OPS_BLOCK_SIZE_Y=4

 OPS_block_size_x = 32 

 OPS_block_size_y = 4 

 16/48 L1/shared 
block "grid2D" decomposed on to a processor grid of 2 x 1  
Finished block decomposition

Total Wall time 0.035862
Reduction result = 32.000000, 32.000000
Result is within 3.333333333333333E+01 % of the expected result
This test is considered FAILED

**********************************

octon {feature/makefiles} ~/OPS-GIT/OPS/apps/c/multiDim3D$ $MPI_INSTALL_PATH/bin/mpirun -np 2 ./multidim_mpi_openacc OPS_BLOCK_SIZE_X=32 OPS_BLOCK_SIZE_Y=4

 OPS_block_size_x = 32 

 OPS_block_size_y = 4 

 16/48 L1/shared 
block "grid3D" decomposed on to a processor grid of 2 x 1 x 1  
Finished block decomposition

Total Wall time 0.046561
Reduction result = 128.000000, 96.000000, 144.000000
Result is within 2.777777777777777E+01 % of the expected result
This test is considered FAILED


**********************************
octon {feature/makefiles} ~/OPS-GIT/OPS/apps/c/poisson$ ./poisson_openacc OPS_BLOCK_SIZE_X=64 OPS_BLOCK_SIZE_Y=4

 OPS_block_size_x = 64 

 OPS_block_size_y = 4 

 16/48 L1/shared 
Grid: 20x20 in 1x1 blocks, 10 iterations, 10 tile height
block "block 0,0" decomposed on to a processor grid of 1 x 1  
Finished block decomposition

Total Wall time 0.048915
Total error: 35.4123597385247
Total error is within 7.085129356528128E+01 % of the expected error
This test is considered FAILED
0.000475


**********************************
octon {feature/makefiles} ~/OPS-GIT/OPS/apps/fortran/multiDim$ make multidim_openacc 
rm -f *.o *.mod
pgfortran -O3 -fast -gopt -Minline  -module /home/mgiles/mudalige/OPS-GIT/OPS/ops/fortran/mod/pgi/openacc -L/home/mgiles/mudalige/OPS-GIT/OPS/ops/fortran/lib -pgc++libs -Mcuda=cc35 -acc -ta=nvidia,cc35 \
		multidim_ops.F90 constants.F90 MPI_OpenACC/*.F90 -o multidim_openacc -lops_for_cuda 
multidim_ops.F90:
constants.F90:
MPI_OpenACC/multidim_copy_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_print_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90:
PGF90-W-0189-Argument number 2 to multidim_reduce_kernel: association of scalar actual argument to array dummy argument (MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90: 53)
  0 inform,   1 warnings,   0 severes, 0 fatal for multidim_reduce_kernel_wrap
multidim_ops.F90:
constants.F90:
MPI_OpenACC/multidim_copy_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_print_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90:
PGF90-W-0189-Argument number 2 to multidim_reduce_kernel: association of scalar actual argument to array dummy argument (MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90: 53)
  0 inform,   1 warnings,   0 severes, 0 fatal for multidim_reduce_kernel_wrap
PGF90-S-0155-Procedures called in a compute region must have acc routine information: multidim_reduce_kernel (MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90: 53)
PGF90-S-0155-Accelerator region ignored; see -Minfo messages  (MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90: 48)
  0 inform,   0 warnings,   2 severes, 0 fatal for multidim_reduce_kernel_wrap
make: *** [multidim_openacc] Error 2


**********************************
There is also the strange case where running the ./test.sh breaks for fortran apps (multiDim, multiDim3D and poisson) but simply executing the commands in the test script manually builds the app .. I think it has somthing to do with the .generated file

**Comment by reguly** [comment]
In fixing the bugs:

Where is __complex__ defined? (it doesn’t seem to be anywhere)

OpenACC ignores the block size parameters

Multidimensional reduction does not seem to be implemented in Fortran. I am highly surprised the OpenMP version works, given we generate invalid code..

**Comment by gihanmudalige** [comment]
I believe almost all the tests work now. Some final issue in compiling the OpenACC version in Fortran (multidim and multidim3D) :  (this is using PGI 16.9)

pgfortran -O3 -fast -gopt  -module /home/mgiles/mudalige/OPS-GIT/OPS/ops/fortran/mod/pgi/openacc -L/home/mgiles/mudalige/OPS-GIT/OPS/ops/fortran/lib -pgc++libs -acc -Minline -ta=nvidia,cc35 -Mcuda=cc35 \
                constants.F90 MPI_OpenACC/*.F90 multidim_ops.F90 -o multidim_openacc -lops_for_cuda
constants.F90:
MPI_OpenACC/multidim_copy_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_print_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90:
PGF90-W-0189-Argument number 2 to multidim_reduce_kernel: association of scalar actual argument to array dummy argument (MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90: 53)
  0 inform,   1 warnings,   0 severes, 0 fatal for multidim_reduce_kernel_wrap
multidim_ops.F90:
constants.F90:
MPI_OpenACC/multidim_copy_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_print_kernel_openacc_kernel.F90:
MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90:
PGF90-W-0189-Argument number 2 to multidim_reduce_kernel: association of scalar actual argument to array dummy argument (MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90: 53)
  0 inform,   1 warnings,   0 severes, 0 fatal for multidim_reduce_kernel_wrap
PGF90-S-0155-Procedures called in a compute region must have acc routine information: multidim_reduce_kernel (MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90: 53)
PGF90-S-0155-Accelerator region ignored; see -Minfo messages  (MPI_OpenACC/multidim_reduce_kernel_openacc_kernel.F90: 48)
  0 inform,   0 warnings,   2 severes, 0 fatal for multidim_reduce_kernel_wrap
multidim_ops.F90:
make: *** [multidim_openacc] Error 2

**Comment by reguly** [comment]
This has never worked - it has just never been tested. We are missing the multidim reduction support in the code generator. I suggest we fix this separately.

**Comment by gihanmudalige** [comment]
Sorry. I thought this at least compiled.  But looking at the tests in test.sh you are right. 
Let me double check the C compilation (as last night it broke) and push my changes to the tests and approve !

**Comment by gihanmudalige** [comment]
Just got back to testing this branch. 
Again openacc is causing trouble. 

octon {feature/makefiles} ~/OPS-GIT/OPS/apps/c/CloverLeaf$  ./cloverleaf_openacc OPS_BLOCK_SIZE_X=64 OPS_BLOCK_SIZE_Y=4[octon:09183] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ../../../../../orte/mca/ess/singleton/ess_singleton_module.c at line 458
[octon:09183] [[INVALID],INVALID] ORTE_ERROR_LOG: A system-required executable either could not be found or was not executable by this user in file ../../../../../orte/mca/ess/singleton/ess_singleton_module.c at line 166
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    orte_init:startup:internal-failure
But I couldn't open the help file:
    /proj/pgi/linux86-64/2018/mpi/openmpi-2.1.2/share/openmpi/help-orte-runtime: No such file or directory.  Sorry!
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    mpi_init:startup:internal-failure
But I couldn't open the help file:
    /proj/pgi/linux86-64/2018/mpi/openmpi-2.1.2/share/openmpi/help-mpi-runtime.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[octon:9183] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

The above work if you run it with mpirun. (i.e. mpirun -np 1 ././cloverleaf_openacc )
I will try and rebuild a different mpi implementation to check this out. But perhaps you can check also  and let me know the source file you used to get it working. 
I am using pgi 18 with openmpi in /opt

**Comment by reguly** [comment]
This was an existing issue in master as well. But I have updated the makefiles so plain openacc does not require MPI anymore.

**Comment by gihanmudalige** [comment]
I had to do some minor changes and reinstall mpich with PGI to get things to work. OK so here is where we are at with the testing:


C/C++ API
CloverLeaf2D - passed
CloverLeaf3D - passed
CloverLeaf_3D_HDF5 - passed
complex-numbers - openacc does not compile (seems to not like the __complex__ for variables)
mb_shsgc - passed
multiDim - passed
multiDim3D - passed
multiDim_HDF5 - passed
poisson - passed
shsgc - passed
TeaLeaf - passed

Fortran API

poisonn - openacc does not compile
shsgc - openacc does not compile
multiDim - openacc does not compile
multiDim3D - openacc does not compile

So if you are happy with this, I think we can merge.

**Comment by reguly** [comment]
Pushed a fix for shsgc and poisson fortran compilation issues. shsgc however does not validate. multiDim issues are unrelated.

**Pull request merged**
