### PR TITLE
C make config

### PR DESCRIPTION
**Pull request by jpmeng**
This pull is intended to submit a few changes on supporting the CMake package configuration so that the users can link the OPS API in their CMakeLists.txt by 

1. Add the following sentences

```cmake
set(OPS_DIR ${OPS_ROOT})
find_package(OPS PATHS ${OPS_DIR}/lib/cmake)
if (NOT OPS_FOUND)
    message(FATAL_ERROR "We cannot find the OPS library!")
endif()
```

​    This is better to be call after searching all other dependences like HDF5, CUDA and OpenCL etc. Otherwise, there will be warning messages and relevant APIs will not be included.

2. Specify the OPS_ROOT as required.

Other changes include

1.  The GPU_ARCH directive for specifying the GPU architecture
2. Replace "fatal_error" message to a notice if compilers other than GNU, INTEL are used. In this case, the compiler flags may be supplied by using -DCFLAG and -DCXXFLAG 
3. Replace MPI_COMM_WORLD with OPS_MPI_GLOBAL so that the code better fit the MPMD parallel model.

### CODE REVIEW

**Comment by gihanmudalige** [comment]
clover.in is a symlink to the actual text files used as input configs as I remember.  Was the symlink changed ?

**Comment by jpmeng** [comment]
> clover.in is a symlink to the actual text files used as input configs as I remember. Was the symlink changed ?

Perhaps, it was changed to a real copy of one set of parameters sometime. But,  I think there is no negative impact. Just very strange: there is no local modification in the commit but somehow, occurred locally. not sure if it is because the encoding of git.

**Comment by jpmeng** [comment]
It seems the CI test is not triggered for a pull request from a forked repo. I have tested locally, all look fine.

**Review by gihanmudalige — APPROVED** [review]

**Comment by gihanmudalige** [comment]
you are good to merge

**Pull request merged**
