### PR TITLE
Just to enable testing in other source trees without cahnges

### PR DESCRIPTION
**Pull request by reguly**

### CODE REVIEW

**Comment by gihanmudalige** [comment]
This is a very good idea. You probably do not need source_pgi though. Let me do the same for any other source file before we merge.

**Comment by reguly** [comment]
Did a quick find and replace!

**Comment by gihanmudalige** [comment]
This is also fine. The only thing I am wondering is what if the code was not downloaded as a git repo. Will this still work ?

**Comment by reguly** [comment]
Since this is for internal use only (testing), I wouldn't worry about it...

**Pull request merged**
