### PR TITLE
OPS implementation for Fortran code of Laplace

### PR DESCRIPTION
**Pull request by Ashutosh-Londhe**
Added Fortran implementation of Laplace
Implemented OPS version on Laplace Fortran code

### CODE REVIEW

**Comment by gihanmudalige** [comment]
@Ashutosh-Londhe does the code generator work on this ? Does it produce the different parallel versions ?

**Comment by Ashutosh-Londhe** [comment]
> @Ashutosh-Londhe does the code generator work on this ? Does it produce the different parallel versions ?

Code generator able to generate following executables
1. laplace_seq
2. laplace_mpi
3. laplace_openmp
4. laplace_mpi_openmp
5. laplace_cuda
6. laplace_mpi_cuda

All above mentioned able to generate correct output

**Comment by reguly** [comment]
So far so good. Please add the intermediate steps too - although ops_par_loops will require code generation to compile. However, it will be very interesting and important to see how we can gradually move an application to use OPS, loop by loop.

**Comment by gihanmudalige** [comment]
I think this is good for getting an initial understanding of the Fortran API and checking if the backend is working. However I agree with @reguly that it would be important to add the intermediate steps to elaborate on the conversion process. Our colleagues at Uni of Newcastle might like to see this, given they will do a bit chunk of the SENGA+ conversion.  So lets plan to add this intermediate steps later down the line.  I will approve this PR based on this.

**Review by gihanmudalige — APPROVED** [review]

**Comment by gihanmudalige** [comment]
I think we are ok to merge this. @reguly if you are ok then do approve. I think we can add the other middle steps a bit later as currently @Ashutosh-Londhe is getting up to speed with OPS and we need to start working on SENGA+

**Review by reguly — APPROVED** [review]

**Pull request merged**
