### PR TITLE
Restructuring device backend files

### PR DESCRIPTION
**Pull request by reguly**
Here is the general idea:
All target-specific API uses go into: xx/ops_xx_common.cpp (functions shared between seq and mpi), xx/ops_xx_singlenode.cpp (functions only for seq), xx/ops_xx_rt_support_kernel.c[pp|u] (device kernels for seq), and mpi/ops_mpi_rt_support_xx.cpp (for functions only for mpi).

Adding a new device backend should be reasonably trivial now - need to only implement kernels in the backend, memory management and device management functions, without essentially any code duplication between backends.

Please review and comment on structure.

### CODE REVIEW

**Comment by reguly** [comment]
@gihanmudalige @jpmeng please let me know :)

**Comment by gihanmudalige** [comment]
@jpmeng could you see whats causing the CI to break in this PR ? Would be very helpful, thanks.

**Review by gihanmudalige — APPROVED** [review]

**Comment by gihanmudalige** [comment]
Running an initial rest of Poisson app leads to an OpenCL error. This is an isue with this branch, where develp branch did not have this error. 

That said, perhaps we should remove OpenCL and move on to the SYCL implementation. 

/opt/intel/oneapi/2021.3/mpi/2021.3.0//bin/mpicxx -qopenmp -O3 -g -xHost -qopenmp -qopt-report -std=c++11 -qopt-zmm-usage=high  -DOPS_MPI -DOPS_LAZY -I-I/opt/cuda/10.2.89/toolkit//include -I/rr-home/gihan/OPS/ops/c/include -L/rr-home/gihan/OPS/ops/c/lib/intel -L/opt/cuda/10.2.89/toolkit//lib64 poisson_ops.cpp   ./CUDA/poisson_kernels_mpi_tiled_cu.o -lcudart   -lops_mpi_cuda -o poisson_mpi_cuda_tiled
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
/opt/intel/oneapi/2021.3/mpi/2021.3.0//bin/mpicxx -O3 -g -xHost -qopenmp -qopt-report -std=c++11 -qopt-zmm-usage=high    -I/opt/cuda/10.2.89/toolkit//include  -I/rr-home/gihan/OPS/ops/c/include -I. \
                -c -o ./OpenCL/poisson_opencl_kernels.o ./OpenCL/poisson_opencl_kernels.cpp
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
/opt/intel/oneapi/2021.3/mpi/2021.3.0//bin/mpicxx -O3 -g -xHost -qopenmp -qopt-report -std=c++11 -qopt-zmm-usage=high   -I/rr-home/gihan/OPS/ops/c/include -L/rr-home/gihan/OPS/ops/c/lib/intel -L/opt/cuda/10.2.89/toolkit//lib64 -lOpenCL poisson_ops.cpp  ./OpenCL/poisson_opencl_kernels.o -I.  -lops_opencl -o poisson_opencl
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
/opt/intel/oneapi/2021.3/mpi/2021.3.0//bin/mpicxx -O3 -g -xHost -qopenmp -qopt-report -std=c++11 -qopt-zmm-usage=high   -I/opt/cuda/10.2.89/toolkit//include  -I/rr-home/gihan/OPS/ops/c/include -I. -DOPS_MPI \
                -c -o ./OpenCL/poisson_mpi_opencl_kernels.o ./OpenCL/poisson_opencl_kernels.cpp
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
/opt/intel/oneapi/2021.3/mpi/2021.3.0//bin/mpicxx -O3 -g -xHost -qopenmp -qopt-report -std=c++11 -qopt-zmm-usage=high  -DOPS_MPI  -I/rr-home/gihan/OPS/ops/c/include -L/rr-home/gihan/OPS/ops/c/lib/intel -L/opt/cuda/10.2.89/toolkit//lib64 -lOpenCL poisson_ops.cpp  ./OpenCL/poisson_mpi_opencl_kernels.o -I.   -lops_mpi_opencl -o poisson_mpi_opencl
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
ld: /rr-home/gihan/OPS/ops/c/lib/intel/libops_mpi_opencl.a(ops_mpi_decl_mpi.o): in function `ops_dat_deep_copy(ops_dat_core*, ops_dat_core*)':
/rr-home/gihan/OPS/ops/c/src/mpi/ops_mpi_decl.cpp:218: undefined reference to `ops_internal_copy_device(ops_kernel_descriptor*)'
ld: /rr-home/gihan/OPS/ops/c/src/mpi/ops_mpi_decl.cpp:218: undefined reference to `ops_internal_copy_device(ops_kernel_descriptor*)'
make: *** [/rr-home/gihan/OPS/ops/../makefiles/Makefile.c_app:155: poisson_mpi_opencl] Error 1

**Review by bgd54 — COMMENTED** [review]
I removed the old HIP generator. The `ops_gen_mpi_cuda(... hip=1)` generates slightly different code (e.g. it does not use xx_OPSCONSTANT variants for globals, `ops_internal_this_is_stupid`). It should be retested.

**Comment by gihanmudalige** [comment]
Testing the ADI application gives the following error: (this is not occurring in the develop branch)

mpiicpc -std=c++11 -fp-model strict -fp-model source -prec-div -prec-sqrt -qopenmp   -I/rr-home/gihan/OPS/ops/c/include -I/opt/hdf5/1.8.18/intel/15.0u6/impi/5.0u3//include -L/rr-home/gihan/OPS/ops/c/lib/intel adi.cpp -lops_seq -lops_hdf5_seq -lops_trid_seq -L/rr-home/gihan/tridsolver/scalar/libtrid/lib -ltridcpu -L/opt/hdf5/1.8.18/intel/15.0u6/impi/5.0u3//lib -lhdf5_hl -lhdf5 -lz -o adi_dev_seq
ld: /rr-home/gihan/OPS/ops/c/lib/intel/libops_hdf5_seq.a(ops_hdf5.o): in function `write_buf_hdf5(char const*, char const*, ops_dat_core* const&, int, int const*, char*)':
/rr-home/gihan/OPS/ops/c/src/externlib/ops_hdf5.cpp:1707: undefined reference to `split_h5_name(char const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
ld: /rr-home/gihan/OPS/ops/c/src/externlib/ops_hdf5.cpp:1713: undefined reference to `h5_type(char const*)'
ld: /rr-home/gihan/OPS/ops/c/lib/intel/libops_hdf5_seq.a(ops_hdf5.o): in function `H5_dataset_space(int, int, unsigned long long const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, char const*, std::vector<int, std::allocator<int> >&, int&, int&)':
/rr-home/gihan/OPS/ops/c/src/externlib/ops_hdf5.cpp:1667: undefined reference to `h5_type(char const*)'
ld: /rr-home/gihan/OPS/ops/c/lib/intel/libops_hdf5_seq.a(ops_hdf5.o): in function `write_buf_hdf5(char const*, char const*, ops_dat_core* const&, int, int const*, char*)':
/rr-home/gihan/OPS/ops/c/src/externlib/ops_hdf5.cpp:1707: undefined reference to `split_h5_name(char const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
ld: /rr-home/gihan/OPS/ops/c/src/externlib/ops_hdf5.cpp:1713: undefined reference to `h5_type(char const*)'
make: *** [Makefile:165: adi_dev_seq] Error 1

**Comment by reguly** [comment]
Fixed it - was an issue from the previous pull request extending HDF5...

**Pull request merged**
