### PR TITLE
Feature/windows rebased

### PR DESCRIPTION
**Pull request by reguly**
Allows compilation under windows with Intel compilers

### CODE REVIEW

**Comment by gihanmudalige** [comment]
I seem to be getting invalid device symbols for cuda apps (even though I think the correct NV_ARCH flag is used):

octon {feature/windows_rebased} ~/OPS-GIT/OPS/apps/c/CloverLeaf$ ./cloverleaf_cuda OPS_BLOCK_SIZE_X=64 OPS_BLOCK_SIZE_Y=4

 OPS_block_size_x = 64 

 OPS_block_size_y = 4 

 16/48 L1/shared 
 Clover version 1.000000
Output file clover.out opened. All output will go there
./CUDA/clover_leaf_kernels.cu(40) : cutilSafeCall() Runtime API error : invalid device symbol.

**Comment by reguly** [comment]
Fixed!

**Comment by gihanmudalige** [comment]
Ahh .. missed that !
Tests running now.

**Comment by gihanmudalige** [comment]
OK. this is fine to go. Tests passed (except for the usual OpenACC and currently broken TeaLeaf OpenCL)

**Pull request merged**
