### PR TITLE
Feature/tutorial

### PR DESCRIPTION
**Pull request by reguly**
This request pulls in a step-by-step tutorial describing how to convert an application to use OPS.

### CODE REVIEW

**Comment by reguly** [comment]
Makefiles have been updated, things build without HDF5 now. Also, only building backends for which env flags are set up

**Comment by gihanmudalige** [comment]
I assume the new application in tutorials needs to be added to the testing suite ?

**Comment by gihanmudalige** [comment]
There is an issue in ops_mpi_partition.c when running CloverLeaf_3D_HDF5. Try running :
export OMP_NUM_THREADS=2;$MPI_INSTALL_PATH/bin/mpirun -np 10 ./cloverleaf_mpi_openmp

**Comment by gihanmudalige** [comment]
I think this is ok to merge now .. tests passed

**Pull request merged**
