### PR TITLE
Pulls in the C++ conversion and thread safety updates

### PR DESCRIPTION
**Pull request by reguly**

### CODE REVIEW

**Comment by gihanmudalige** [comment]
I have rebased this now on master. Now, I am getting an errors with pgcc when testing this branch :

pgc++ -O3 -fast -gopt  -std=c++11  -Iinclude -I/rr-home/gihan/HDF5-PGI-18/include -I/opt/cuda/9.1.85/toolkit//include -I/opt/cuda/9.1.85/toolkit//include -c src/core/ops_lib_core.cpp -o obj/pgi/ops_lib_core.o
"src/core/ops_lib_core.cpp", line 1445: error: identifier "isnan" is undefined
                    if (  isnan(((double *)dat->data)[offset])  ) {
                          ^

"src/core/ops_lib_core.cpp", line 1451: error: identifier "isnan" is undefined
                    if (  isnan(((float *)dat->data)[offset])  ) {
                          ^

2 errors detected in the compilation of "src/core/ops_lib_core.cpp".
Makefile:81: recipe for target 'obj/pgi/ops_lib_core.o' failed
make: *** [obj/pgi/ops_lib_core.o] Error 2

**Comment by reguly** [comment]
Pushed a fix for this, changing it to std::isnan

**Comment by gihanmudalige** [comment]
Previous error fixed. 
New issue in PGI compiled CloverLeaf_3D_HDF5 :

kos {feature/lib_thread_safety} ~/OPS/apps/c/CloverLeaf_3D_HDF5$ KMP_AFFINITY=compact OMP_NUM_THREADS=20 ./cloverleaf_openmp
 Clover version 1.000000
Output file clover.out opened. All output will go there
Global x_min = 2, y_min = 2, z_min = 2
Global x_max = 98, y_max = 98, z_max = 98
terminate called after throwing an instance of 'OPSException'
  what():  Error: ops_decl_stencil_hdf5: Unequal dims of stencil 0,0,0:-3,0,0 dims on file 3, dims specified 0
Aborted

**Comment by gihanmudalige** [comment]
Double checked with PGI compilers and regenerating the cloverdata.h5 file. But still get the above error.  There is no different between the cloverdata.h5s built with intel and pgi.

**Comment by gihanmudalige** [comment]
Ok the above error is solved. Now stuck with PGI compilers compiling, multidim_HDF5:

/rr-home/gihan/MPICH-PGI-18//bin/mpicxx  -I/rr-home/gihan/OPS/ops/c/include -L/rr-home/gihan/OPS/ops/c/lib/pgi write_ops.cpp -I. ./MPI_OpenMP/write_cpu_kernels.cpp -lops_seq -lops_hdf5_seq -L/rr-home/gihan/HDF5-PGI-18/lib -lhdf5_hl -lhdf5 -lz -o write_seq
write_ops.cpp:
"/rr-home/gihan/OPS/ops/c/include/ops_lib_core.h", line 115: error: expected an
          identifier
  typedef std::complex<double> complexd;
               ^

"/rr-home/gihan/OPS/ops/c/include/ops_lib_core.h", line 115: error: expected a
          ";"
  typedef std::complex<double> complexd;
               ^

"/rr-home/gihan/OPS/ops/c/include/ops_lib_core.h", line 116: error: expected an
          identifier
  typedef std::complex<float> complexf;
               ^

"/rr-home/gihan/OPS/ops/c/include/ops_lib_core.h", line 116: error: expected a
          ";"
  typedef std::complex<float> complexf;
               ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 116: error: expected
          an identifier
  inline int type_error(const std::complex<float> *a, const char *type) {
                                   ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 116: error: expected a
          ")"
  inline int type_error(const std::complex<float> *a, const char *type) {
                                   ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 117: error: identifier
          "a" is undefined
    (void)a;
          ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 118: error: identifier
          "type" is undefined
    return strcmp(type, "complexf");
                  ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 120: error: expected
          an identifier
  inline int type_error(const std::complex<double> *a, const char *type) {
                                   ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 120: error: expected a
          ")"
  inline int type_error(const std::complex<double> *a, const char *type) {
                                   ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 120: error: function
          "type_error(int)" has already been defined
  inline int type_error(const std::complex<double> *a, const char *type) {
             ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 121: error: identifier
          "a" is undefined
    (void)a;
          ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 122: error: identifier
          "type" is undefined
    return strcmp(type, "complexd");
                  ^

13 errors detected in the compilation of "write_ops.cpp".
./MPI_OpenMP/write_cpu_kernels.cpp:
"/rr-home/gihan/OPS/ops/c/include/ops_lib_core.h", line 115: error: expected an
          identifier
  typedef std::complex<double> complexd;
               ^

"/rr-home/gihan/OPS/ops/c/include/ops_lib_core.h", line 115: error: expected a
          ";"
  typedef std::complex<double> complexd;
               ^

"/rr-home/gihan/OPS/ops/c/include/ops_lib_core.h", line 116: error: expected an
          identifier
  typedef std::complex<float> complexf;
               ^

"/rr-home/gihan/OPS/ops/c/include/ops_lib_core.h", line 116: error: expected a
          ";"
  typedef std::complex<float> complexf;
               ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 116: error: expected
          an identifier
  inline int type_error(const std::complex<float> *a, const char *type) {
                                   ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 116: error: expected a
          ")"
  inline int type_error(const std::complex<float> *a, const char *type) {
                                   ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 117: error: identifier
          "a" is undefined
    (void)a;
          ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 118: error: identifier
          "type" is undefined
    return strcmp(type, "complexf");
                  ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 120: error: expected
          an identifier
  inline int type_error(const std::complex<double> *a, const char *type) {
                                   ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 120: error: expected a
          ")"
  inline int type_error(const std::complex<double> *a, const char *type) {
                                   ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 120: error: function
          "type_error(int)" has already been defined
  inline int type_error(const std::complex<double> *a, const char *type) {
             ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 121: error: identifier
          "a" is undefined
    (void)a;
          ^

"/rr-home/gihan/OPS/ops/c/include/ops_internal1.h", line 122: error: identifier
          "type" is undefined
    return strcmp(type, "complexd");
                  ^

"./MPI_OpenMP/write_kernel_cpu_kernel.cpp", line 109: warning: unrecognized GCC
          pragma
        #pragma GCC ivdep
                    ^

13 errors detected in the compilation of "./MPI_OpenMP/write_cpu_kernels.cpp".
Makefile:182: recipe for target 'write_seq' failed
make: *** [write_seq] Error 2

**Comment by reguly** [comment]
Ah, that just needs -std=c++11 in the Makefile

**Comment by gihanmudalige** [comment]
There are still some issues with the Fortran apps : 

1. Specifying a value for OPS_BLOCK_SIZE_X and OPS_BLOCK_SIZE_Y causes issues, without it works fine (compiled with PGI 18)

kos {feature/lib_thread_safety} ~/OPS/apps/fortran/multiDim$ $MPI_INSTALL_PATH/bin/mpirun -np 2 ./multidim_mpi_cuda OPS_BLOCK_SIZE_X=64 OPS_BLOCK_SIZE_Y=4
Attempting to use an MPI routine before initializing MPICH
Attempting to use an MPI routine before initializing MPICH
kos {feature/lib_thread_safety} ~/OPS/apps/fortran/multiDim$ $MPI_INSTALL_PATH/bin/mpirun -np 2 ./multidim_mpi_cuda

 16/48 L1/shared 
block "grid2D" decomposed on to a processor grid of 2 x 1  
Finished block decomposition
Max total runtime =       0.0004449 seconds
Reduction result =       40.0000000      40.0000000
Reduction result is within    0.0000000E+00% of the expected result
This test is considered PASSED

2.  poisson_mpi_cuda and shsgc_mpi_cuda not validating (again using PGI 18 compilers)

/rr-home/gihan/MPICH-PGI-18//bin/mpif90 -O3 -fast -gopt  -module /rr-home/gihan/OPS/ops/fortran/mod/pgi/cuda -L/rr-home/gihan/OPS/ops/fortran/lib -pgc++libs -DOPS_WITH_CUDAFOR -Mcuda=cc60 -Mcuda=cc60 -DOPS_MPI constants.F90 CUDA/*_cuda_kernel.CUF poisson_ops.F90 \
        -o poisson_mpi_cuda -lops_for_mpi_cuda 
constants.F90:
CUDA/poisson_error_kernel_cuda_kernel.CUF:
CUDA/poisson_initialguess_kernel_cuda_kernel.CUF:
CUDA/poisson_populate_kernel_cuda_kernel.CUF:
CUDA/poisson_stencil_kernel_cuda_kernel.CUF:
CUDA/poisson_update_kernel_cuda_kernel.CUF:
poisson_ops.F90:
(failed reverse-i-search)`moir': /rr-home/gihan/MPICH-PGI-18//bin/mpif90 -O3 -fast -gopt  -module /rr-home/gihan/OPS/ops/fortran/^Cd/pgi/cuda -L/rr-home/gihan/OPS/ops/fortran/lib -pgc++libs -DOPS_WITH_CUDAFOR -Mcuda=cc60 -Mcuda=cc60 -DOPS_MPI constants.F90 CUDA/*_cuda_kernel.CUF mblock_ops.F90         -o mblock_mpi_cuda -lops_for_mpi_cuda
kos {feature/lib_thread_safety} ~/OPS/apps/fortran/poisson$ $MPI_INSTALL_PATH/bin/mpirun -np 2 ./poisson_mpi_cuda 

kos {feature/lib_thread_safety} ~/OPS/apps/fortran/poisson$ $MPI_INSTALL_PATH/bin/mpirun -np 2 ./poisson_mpi_cuda 

 16/48 L1/shared 
block "block 1, 1          " decomposed on to a processor grid of 1 x 1  
block "block 2, 1          " decomposed on to a processor grid of 1 x 1  
block "block 1, 2          " decomposed on to a processor grid of 1 x 1  
block "block 2, 2          " decomposed on to a processor grid of 1 x 1  
Finished block decomposition
 Max total runtime =    2.216816186904907      seconds
Total error:              NaN
Total error is within             NaN% of the expected error
This test is considered FAILED

**Comment by gihanmudalige** [comment]
All tests passing now (except the usual OpenACC apps).   If we need to look into performance numbers, we need a bit more time to explore, before merging ?

**Comment by gihanmudalige** [comment]
I have got OpenSBLI to work. But their Makefile detailed in the docs need to change with our new naming conventions.  Let me put a pull request to OpenSBLI repo before we merge this. I shold be able to do this soon !

**Pull request merged**
