### PR TITLE
Feature/data access

### PR DESCRIPTION
**Pull request by reguly**
This introduces API to give users access to OPS data. It also removes ops_fetch_dat

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Ok running tests  now. 
Looking at the documentation, I was not clear what is meant by "chunk" and "chunk index" ?

**Comment by reguly** [comment]
This is not something that is in OPS yet. In the future, we may want to do shared memory partitioning too (e.g. multi-GPU from a single process), and it helps with that. Similar concept to what the reference CloverLeaf uses, where you can have multiple chunks in the same process.

**Comment by gihanmudalige** [comment]
OK. we will need to write this in the docs. So I assume currently chunk index is simply 0 as there is only one chunk ?  (again this needs to be updated in the docs)

**Comment by reguly** [comment]
That's right, we should note that

**Comment by reguly** [comment]
Pushed a clarification to the docs.

**Comment by gihanmudalige** [comment]
I am getting a segfault for CloverLeaf_3D_HDF5. Sorry did not have time to dig in to it. Perhaps you know of a quick fix ?

octon {feature/data_access} ~/OPS-GIT/OPS/apps/c/CloverLeaf_3D_HDF5$ export OMP_NUM_THREADS=10;$MPI_INSTALL_PATH/bin/mpirun -np 2 ./cloverleaf_mpi_tiled OPS_TILING OPS_TILING_MAXDEPTH=6
APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)

**Comment by reguly** [comment]
I am unable to reproduce this issue...

**Comment by gihanmudalige** [comment]
OK. I think its a mixup with compilers. I am trying again.

**Comment by gihanmudalige** [comment]
Ok all the test in the current scripts PASS. 
So for the Fortran side ... ops_fetch_dat()  seems to still work.  Is this expected ? Do we not need the FORTRAN API also updated with these new fetch API calls ?

**Comment by reguly** [comment]
Pushed in the fortran side.

**Comment by gihanmudalige** [comment]
I cannot see any further pushes to this branch

**Comment by gihanmudalige** [comment]
OK All tests pass.

**Pull request merged**
