### PR TITLE
Feature/cmake

### PR DESCRIPTION
**Pull request by jpmeng**
Hi Gihan, 

The CMake  for compiling the ops/c with the GNU compiler is done, together with a preliminary Gitlab CI/CD YAML which can test the compiling process. If you like, this can be merged into master to silence the warning currently caused by the test-ops command.

Cheers,

Jianping

### CODE REVIEW

**Comment by reguly** [comment]
Thank Jianping - is this currently not capable of building the apps? As for the backend, it seems good to me for GNU!

**Comment by jpmeng** [comment]
Hi Istvan,

Yes, I will try to sort out APPS within this week and/or next week.  Here, I just wanted to first remove the wrong CI/CD testing failure. 

Cheers,

Jianping


> Thank Jianping - is this currently not capable of building the apps? As for the backend, it seems good to me for GNU!

**Comment by gihanmudalige** [comment]
@jpmeng , did you see my comment about the file structure / location ?

**Comment by jpmeng** [comment]
> @jpmeng , did you see my comment about the file structure / location ?

Yes, did I miss anything?

**Comment by jpmeng** [comment]
Hi Gihan,

Perhaps, we can now have a try on merging the Gitlab CI/CI and CMake works?

Cheers,

Jianping

**Comment by gihanmudalige** [comment]
@reguly   .. Are we ok to merge this to maser ? I am inclined to go ahead. But given this is a bit significant, could you take a look ?

**Comment by gihanmudalige** [comment]
OK, other than the inputfiles in the TeaLeaf app (e.g. apps/c/TeaLeaf/Benchmarks/tea_bm_2.in  etc.) being deleted in this, I am fine to approve. When we have these files back in, I can approve !

**Comment by reguly** [comment]
- There are a lot of variables that are not exposed and not have a default. For example, if I set BUILD_OPS_APPS, then it complains about APP_INSTALL missing, but it does not show up in ccmake, and I don't even know what to set it.
- If the default 'python' is 3.x, then I get an error, even though python2.7 exists in my path. Not sure if there is an easy way to fix that
- If I enable OPS_APP_TEST but BUILD_OPS_APPS is not enabled, then there are no tests
- If I enable both, then I get the following error:
> CMake Error at apps/c/multiDim_HDF5/CMakeLists.txt:20 (add_test):
>  Error evaluating generator expression:
>
>   $<TARGET_FILE:read_opencl>
>
> No target "read_opencl"
>
>
>CMake Error at apps/c/multiDim_HDF5/CMakeLists.txt:20 (add_test):
>  Error evaluating generator expression:
>
>    $<TARGET_FILE:write_opencl>
>
>  No target "write_opencl"

**Comment by jpmeng** [comment]
Hi Gihan and Istvan,

Sorry a busy day. I will look at them no later than the early next week. 

Cheers, 

Jianping

**Comment by jpmeng** [comment]
Hi Istvan,

About the Python issue, Could you please let me know which system are you using? It looks Ok under the ubuntu 18.04 where Python2 and Python3 coexist.  

I assume that the translator in the master branch needs Python2. 

Cheers,

Jianping

**Comment by reguly** [comment]
I am using centos 7.6. I  do have both, but the default 'python' executable
points to 3.x.

Yes, we do need python 2 for the translator.

**Comment by jpmeng** [comment]
Perhaps, the cmake find_python2 package doesn't work well under centos 7.6? I just tested Ubuntu 20.04, looks Ok again.  If you  can help to test two options: 1. Update to latest CMake. 2. Tell CMake the Python2 directory manually by using PYTHON_LIBRARY             -  path to the python library
PYTHON_INCLUDE_DIR         - path to where Python.h is found

Thanks.

**Comment by reguly** [comment]
Yes, I specified -DPython2_EXECUTABLE, then it found the right one.

**Comment by jpmeng** [comment]
Thanks Istvan. 
I will then document this in readme. Is your Python2 environment configured by "module" in a login node like machine?  if it is, I can also explain it in documents. I will also try archer and see.

**Comment by gihanmudalige** [comment]
Any further updates for this, or are we ok to merge ?

**Comment by jpmeng** [comment]
Hi Gihan, I am revising the readme and will let me you know when it is ready. 

Jianping 
> Any further updates for this, or are we ok to merge ?

**Comment by jpmeng** [comment]
Hi Gihan,

I've checked these inputfiles.  They are not deleted but moved up to the TeaLeaf directory for the convenience of automatic tests. Now we use a unified script for this purpose, which copies all necessary files (including these input files) to a temporary directory  and assembles the tests. So, It is more convenient to have same layout for all applications. Is this Ok?

Jianping  
> OK, other than the inputfiles in the TeaLeaf app (e.g. apps/c/TeaLeaf/Benchmarks/tea_bm_2.in etc.) being deleted in this, I am fine to approve. When we have these files back in, I can approve !

**Comment by jpmeng** [comment]
Hi Both,

I have revised the README.md to describe how to use the CMake to build the library and applications. Also, the  warning messages are improved so that if CMake cannot find HDF5, Python etc, it will warn and give instructions on how to specify the path manually. 

Istvan,  

About the following two issues:

1. If I enable OPS_APP_TEST but BUILD_OPS_APPS is not enabled, then there are no tests
 Currently the tests are mainly from applications. So, if not to build applications, there will be no tests.  

2. If I enable both, then I get the following error:
CMake Error at apps/c/multiDim_HDF5/CMakeLists.txt:20 (add_test):
Error evaluating generator expression:

$<TARGET_FILE:read_opencl>

No target "read_opencl"

CMake Error at apps/c/multiDim_HDF5/CMakeLists.txt:20 (add_test):
Error evaluating generator expression:

$<TARGET_FILE:write_opencl>

No target "write_opencl"

It looks Ok here (see also, https://gitlab.com/op-dsl-ci/ops-ci/-/jobs/872521573). Possibly, this is caused by the fact of not finding Python2 since CMake always copies the application codes to temporary directories and  call the ops.py to generate the optimised codes.  Could you please retry and let me know any further issues? 

Cheers,

Jianping

**Comment by reguly** [comment]
Is it absolutely necessary to use cmake 3.18? It is quite recent, most systems will not have it. It has gone away with the current version!

Cheers,
Istvan

**Comment by jpmeng** [comment]
Istvan,

It is found that CMake higher that 3.17 presents behaviour different from 3.17 in finding HDF5  and better capabilities in finding OpenCL ( For 3.17,  the path had to be manual specified in my tests) .  So, the mitigation here is a script provided in README.md, which can help to update the CMake easily.  

Jianping

**Review by reguly — APPROVED** [review]

**Review by gihanmudalige — APPROVED** [review]
Excellent. OK to merge.

**Pull request merged**
