### PR TITLE
Feature/remove generated code and GitHub action to commit them

### PR DESCRIPTION
**Pull request by jpmeng**
This pull request is for:
1. Remove all generated codes for apps from the code repository 
2. Automatically push generated codes for apps to another OPS-APPS repository during a pull request if any files in the ops_translator or the apps are changed.

### CODE REVIEW

**Review by reguly — APPROVED** [review]

**Comment by gihanmudalige** [comment]
@jpmeng have you removed the test.sh scripts in each application directory. I think it would be good to have these in the main OPS repo for people to know the various version to run.

**Comment by jpmeng** [comment]
> @jpmeng have you removed the test.sh scripts in each application directory. I think it would be good to have these in the main OPS repo for people to know the various version to run.

@gihanmudalige No, I just removed generated codes

**Comment by gihanmudalige** [comment]
well CLoverLeaf and CloverLeaf_3D_HDF5 is missing the test.sh ... will put these back

**Comment by gihanmudalige** [comment]
[ ] Need to move Fortran apps also to OPS-APPS repo

**Review by gihanmudalige — APPROVED** [review]

**Pull request merged**
