### PR TITLE
Read & write constants (scalars and small arrays) with HDF5

### PR DESCRIPTION
**Pull request by reguly**

### CODE REVIEW

**Comment by reguly** [comment]
I pushed support for char arrays  -keep in mind you'll have to provide the length of the string too. std::string support we can't do unfortunately through the C API.

**Comment by jpmeng** [comment]
Thanks. I realised that the string support was already there later. No problem at all.  Probably we can merge it now?

**Comment by reguly** [comment]
@gihanmudalige please have a look and approve

**Comment by gihanmudalige** [comment]
Testing multiDim_HDF5 produces HDF5 errors:

Writing 'my_const' to file 'write_data.h5'
Writing constant to write_data.h5
HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: H5D.c line 192 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
..........
..........

**Comment by reguly** [comment]
Works perfectly fine for me on Octon, with Intel compilers, with both dev_seq and dev_mpi. Did you remove the previous HDF5 file?

**Comment by gihanmudalige** [comment]
The tests remove the hdf5 files prior to testing. The following is what I ran:

rm -rf write_data.h5 read_data.h5;
$MPI_INSTALL_PATH/bin/mpirun -np 20 ./write_mpi
$MPI_INSTALL_PATH/bin/mpirun -np 20 ./read_mpi

The write_mpi works file. The subsequent read is the one that produces the errors.

**Comment by gihanmudalige** [comment]
Rebased on current master. But still the problem persists.

**Comment by reguly** [comment]
Thank you  - I  simply copied the relevant bits of code from OP2 for this.
Any idea where it might go wrong?

**Comment by gihanmudalige** [comment]
Ahhh ... so its simply the OP2 const writing you have done. Could it be due to some multi-block aspect in OPS that was not in OP2 ?

Did you manage to reproduce my error ?

**Comment by reguly** [comment]
This app doesn't use any of that... And it seems to work fine for me on 1-2 processes..

**Comment by gihanmudalige** [comment]
Unless I am mistaken, it seems that in read.cpp you do not read from the correct HDF5 file. The ops_get_const_hdf5 should be reading from write_date.h5.  The following is the corrected lines for getting the values of constants:

  int my_const;
  ops_get_const_hdf5("my_const", 1, "int", (char*)&my_const, "write_data.h5");
  printf("Read const: %d\n", my_const);

  char buffer[50];
  ops_get_const_hdf5("my_text", 11, "char", buffer, "write_data.h5");
  printf("Read text: %s\n", buffer);

Could this actually be the issue @reguly  ?

**Comment by gihanmudalige** [comment]
Ok Seems this was an issue with the multiDim_HDF5 application itself and not the HDF5 I/O in the back end. @reguly I assume that the changes I have made to the application is indeed what you initially meant to do for this application. 
If so, you are good to merge this to master.

**Pull request merged**
