### PR TITLE
Casting to 64 bit ints when doing arithmetics with bytes

### PR DESCRIPTION
**Pull request by reguly**

### CODE REVIEW

**Comment by gihanmudalige** [comment]
Given the pipeline has passed, we should merge.

**Review by gihanmudalige — APPROVED** [review]

**Comment by reguly** [comment]
We need @jpmeng to check if this works with his setup

**Comment by gihanmudalige** [comment]
The CI tests have passed as far as I can see. @jpmeng are there other tests to be done ?

**Comment by jpmeng** [comment]
> We need @jpmeng to check if this works with his setup

Hi Istvan,

Sorry for the delay. I didn't get chance to test my code. 

Yes, strangely, it doesn't work here. 

Could I just double check that modifications only happen at Python files? For example, for the CUDA backend, we only need to revise
` code('long long int dat'+str(n)+' = (block->instance->OPS_soa ? args['+str(n)+'].dat->type_size : args['+str(n)`
and
` code('long long int base'+str(n)+' = args['+str(n)+'].dat->base_offset + ')`?

I didn't recompile the C/C++ part of the library.

Perhaps, could you please send me back the testing codes which using make? I can further compare. 

Cheers,

Jianping

**Pull request merged**
