### PR TITLE
Pulling in a bunch of outstanding commits

### PR DESCRIPTION
**Pull request by reguly**
Main new feature is the data slab extraction data access API. Currently unimplemented for MPI

### CODE REVIEW

**Comment by gihanmudalige** [comment]
CloverLeaf 2D fails with mpi_cuda_tiled. The execution line I used is:
$MPI_INSTALL_PATH/bin/mpirun -np 2 ./cloverleaf_mpi_cuda_tiled OPS_TILING OPS_TILING_MAXDEPTH=6

Is the above correct ?

**Comment by reguly** [comment]
It is, yes - pushed a fix

**Comment by gihanmudalige** [comment]
Changes introduced in commit 224f633c93610a72ec7641b80b0d856bd830c1f8  (CUDA multidim indexing issue fix) now breaks multidim_mpi_cuda

**Comment by reguly** [comment]
Hopefully fixed!

**Comment by gihanmudalige** [comment]
Ok I removed the OpenCL CPU test for multiDIM_HDF5. Other tests pass.

**Pull request merged**
