### PR TITLE
fixing cuda codegen issue with unknown dimension data

### PR DESCRIPTION
**Pull request by reguly**
To address @jpmeng's issue.

### CODE REVIEW

**Comment by jpmeng** [comment]
Hi Istvan,

I have two more small tests into the multidim app, and two issues occur:

1. /home/jianping/CodeDev/OPS/build/apps/c/multiDim/tmp/multidim_ops.cpp:84:3: error: ‘ops_decl_const’ was not declared in this scope; did you mean ‘ops_decl_const2’?
[build]    84 |   ops_decl_const("nx", 1, "int", &nx);
[build]       |   ^~~~~~~~~~~~~~
[build]       |   ops_decl_const2

After commenting out these two ops_decl_const call, I am able to compile and run.

2. At the GPU side, an illegal memory access was encountered for the ops_par_loop call at Line 197, which should be induced the ops_arg_gbl call. 


Jianping

**Comment by jpmeng** [comment]
One further point:
The SoA mode makes the task of retrieving multi-dim ops_dat from H5 file very tricky if   With the AoS, say we are using Python (numpy+h5py), we have to reshape the array two times to get the correct array due to the difference between of C-order  and Fortran-order as well as the memory layout of (d*nx,ny) for multi-dim ops_dat. With SoA, it becomes more difficult. Can we export the array in its shape i.e., (d, nx,ny) to make it easier?

**Comment by jpmeng** [comment]
One further point:
The SoA mode makes the task of retrieving multi-dim ops_dat from H5 file very tricky if   With the AoS, say we are using Python (numpy+h5py), we have to reshape the array two times to get the correct array due to the difference between of C-order  and Fortran-order as well as the memory layout of (d*nx,ny) for multi-dim ops_dat. With SoA, it becomes more difficult. Can we export the array in its shape i.e., (d, nx,ny) to make it easier?

**Comment by reguly** [comment]
Please see the fixes now. Regarding SoA output - @gihanmudalige do we just have to transpose data on the CPU before we write to HDF5?

**Comment by gihanmudalige** [comment]
@reguly , yes, data should be in the same order as it was read in.

**Comment by reguly** [comment]
OK, let's test and merge this, and open another ticket for HDF5 SoA->AoS conversion. @gihanmudalige please run the usual full set of tests.

**Review by gihanmudalige — APPROVED** [review]

**Comment by gihanmudalige** [comment]
HIP in the CI pipeline seems to have been broken due to this. @jpmeng  any ideas ?

**Comment by reguly** [comment]
CUDA doesn't seem to have issues with the same scheme...

**Pull request merged**
