### PR TITLE
GPU halo exchange optimisations and logging optimisations

### PR DESCRIPTION
**Pull request by reguly**
Decomposing in higher dimensions first, and using pinned memory for comms

### CODE REVIEW

**Comment by gihanmudalige** [comment]
any further updates to this ?

**Comment by reguly** [comment]
Please commit in the slight change we made on octon. Otherwise this is it, assuming the tests pass.

**Comment by gihanmudalige** [comment]
Further to my commit message above .. I just tested CloverLeaf_3D_HDF5 for the master branch.  The MPI+OpenCL version gives the correct results for that branch.

**Comment by gihanmudalige** [comment]
Ok seems that the error is coming from the previous merging of the tutorial branch to master.  @reguly  could you try running : 

$MPI_INSTALL_PATH/bin/mpirun -np 20 ./cloverleaf_mpi_opencl OPS_CL_DEVICE=0

Seems there is still an issue with that function pointer technique.

**Comment by gihanmudalige** [comment]
Ok I think I found the issue. We are linking with the seq HDF5 backend for MPI+OpenCL. Doing tests now to see if this is indeed the problem.

**Comment by reguly** [comment]
I pushed in a check for the null function pointer issue. Plus another fix for linking this, but that went to master accidentally. Anyway, should be fixed now.

**Comment by gihanmudalige** [comment]
Most of the big applications are now passing. However there is now a fail for apps/c/multiDim3D 
export OMP_NUM_THREADS=2;$MPI_INSTALL_PATH/bin/mpirun -np 12 ./multidim_mpi_openmp
Not sure why this is causing issues. But probably due to the use of multi-dim dats.

**Comment by gihanmudalige** [comment]
Yes .. this fixed the issues. All tests passed. Do merge.

**Pull request merged**
